#!/bin/bash
# zhangwei13 <alucard.hust@gmail.com>

allServers=(
"server1" "1.1.1.1"
"server2" "127.0.0.1"
)

user=$1

function help() {
	echo `basename $0`" [user] @1(2,3,4...) remoteFile localFile"
	echo `basename $0`" [user] localFile @1(2,3,4...) remoteFile"
	for ((i=0; i<${#allServers[@]}; i+=2)); do
		printf "%2s %15s %20s\n" "$((i/2))" ${allServers[$((i))]} ${allServers[$((i+1))]}
	done
}

if [ -z "$2" ] || [ -z "$3" ] ;then
	help
else

	echo $2 | grep ^@
	if [ $? -eq 0 ]; then
		echo $4 | grep ^@
		if [ ! $? -eq 0 ]; then
			id=${1#\@}
			echo "scp "${allServers[$(($id*2))]} ${allServers[$(($id*2+1))]}:$3 to $4
			scp -r $user@${allServers[$(($id*2+1))]}:$3 $4
			exit 0
		fi
	fi

	echo $3 | grep ^@
	if [ $? -eq 0 ]; then
		echo $2 | grep ^@
		if [ ! $? -eq 0 ]; then
			id=${2#\@}
			echo "scp $2 to "${allServers[$(($id*2))]} ${allServers[$(($id*2+1))]}:$4
			scp -r $2 $user@${allServers[$(($id*2+1))]}:$4
			exit 0
		fi
	fi

	help
fi
