#!/bin/bash
# zhangwei13 <alucard.hust@gmail.com>

allServers=(
"server1" "1.1.1.1"
"server2" "127.0.0.1"
)

function help() {
	echo `basename $0`" @1(2,3,4...) remoteFile localFile"
	echo `basename $0`" localFile @1(2,3,4...) remoteFile"
	for ((i=0; i<${#allServers[@]}; i+=2)); do
		printf "%2s %15s %20s\n" "$((i/2))" ${allServers[$((i))]} ${allServers[$((i+1))]}
	done
}

if [ -z "$1" ] || [ -z "$2" ] ;then
	help
else

	echo $1 | grep ^@
	if [ $? -eq 0 ]; then
		echo $3 | grep ^@
		if [ ! $? -eq 0 ]; then
			id=${1#\@}
			echo "scp "${allServers[$(($id*2))]} ${allServers[$(($id*2+1))]}:$2 to $3
			scp -r root@${allServers[$(($id*2+1))]}:$2 $3
			exit 0
		fi
	fi

	echo $2 | grep ^@
	if [ $? -eq 0 ]; then
		echo $1 | grep ^@
		if [ ! $? -eq 0 ]; then
			id=${2#\@}
			echo "scp $1 to "${allServers[$(($id*2))]} ${allServers[$(($id*2+1))]}:$3
			scp -r $1 root@${allServers[$(($id*2+1))]}:$3
			exit 0
		fi
	fi

	help
fi
